apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-suite-test-component-git-source-alix
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-suite-test-component-git-source-alix
    app.kubernetes.io/part-of: integration-suite-test-application-laul
  name: integration-suite-test-component-git-source-alix
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: integration-suite-test-component-git-source-alix
status:
  loadBalancer: {}
